### ISSUE TITLE
Consolidate server logging

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/scimodom#100]
### Aims/objectives.

For production.

### A clear and concise description of todo items.

- To "harmonize" logging throughout the app, *e.g.* some modules/classes have no logging at all, logging levels are not used consistently *i.e.* some info should actually be debug, and vice versa, *etc.*
- Some functions are defined in utils but are not used. Currently, logging is configured in [config.py](https://github.com/dieterich-lab/scimodom/blob/832eb50a0b997d74465be36f254ad66dc12bdc89/server/src/scimodom/config.py)
- What is the difference between `from flask import current_app`, `current_app.logger` and `import logging`, `logging.getLogger(__name__)`?
- For production, logs are accessed *e.g.* with `podman-compose logs`. I believe they are somewhere under /scimodom_data/containers/, but where exactly I don't know. Is this "configurable"? *e.g* how long are logs kept? What if we need to go back a few days? Do we need a more flexible solution *e.g.* app-only logging, rotating logs?

Re format, see also [injecting-request-information](https://flask.palletsprojects.com/en/2.3.x/logging/#injecting-request-information).

**Comment by HaraldWilhelmi** [comment]
The command "podman-compose logs" just grants access to the stdout/stderr of the applications running in the container. One possible approach is this:
* Log the level WARNING and up to stderr so that they are visible with "podman-compose logs".
* Write INFO and above to some log file.
* Write DEBUG too to the log file if a DEBUG option is given.
We could also make the log file accessible from outside the container by adding a bind volume to the docker-compose.yml.
